= TDCF通報式WMO CSV表の処理
:toc:
:usc: _

== WMO CSVのファイル構造
=== レポジトリ
次の3つのレポジトリに分かれて管理されている:

* https://github.com/wmo-im/GRIB2
* https://github.com/wmo-im/BUFR4 (CREXを含む)
* https://github.com/wmo-im/CCT

ブランチ:

* `main` - 現行最新通報式
* `FT2026-1` - 照会中ファストトラック
* `FT2025-2` (削除済み) - 前回のファストトラック

=== GRIB2符号表

* `GRIB2/GRIB2_CodeFlag`{usc}__s{usc}n__``{usc}CodeTable{usc}en.csv`` - 符号表__s__._n_
* `GRIB2/GRIB2_CodeFlag`{usc}__s{usc}n__``{usc}FlagTable{usc}en.csv`` - フラグ表__s__._n_
* `GRIB2/GRIB2_CodeFlag`{usc}4{usc}2{usc}__d{usc}k__``{usc}CodeTable{usc}en.csv`` - 符号表4.2に限り、分野__d__カテゴリ__k__ で別ファイルになっている
* `GRIB2/notes/CodeFlag_notes.csv` - 注釈番号から注釈文を与える
* `GRIB2/notes/CodeFlag_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここで節番号 _s_ = 1,3,4,5,7; 表番号 _n_ = 0以上の整数(現行規定は336まで使用); 分野番号 _d_ = 0..255 (符号表0.0); カテゴリ番号 _k_ = 0..255 (符号表4.1)である。

符号表は次のフィールドを持つ:

|===
|列名 |名称・用法
|Title_en |表の標題(全行共通)
|SubTitle_en |表の副題(全行共通、符号表4.1及び4.2で非空白)
|CodeFlag |「数字符号」または「ビット」
|Value |「値」。フラグ表で非空白
|MeaningParameterDescription_en |意味
|Note_en |注記表示(非空白の場合、意味に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,CodeFlag_notes.csvを参照)
|UnitComments_en |「単位」。符号表4.2で使用
|Status |状態
|===

<<Status,Statusは表示に反映しない(後述)>>ので、
全行共通のTitle_en, SubTitle_enを除いて
通報式文書ではCodeFlag, Value, MeaningParameterDescription_en+Note_enの
3列の表が書かれることになる。

notes/CodeFlag_notes.csv は次のフィールドを持つ:

|===
|列名 |名称・用法
|noteID |注釈番号(表本体から参照するキー)
|note |注釈文字列
|===

notes/CodeFlag_table.csv は次のフィールドを持つ:

|===
|列名 |名称・用法
|tableNo |表番号(_s.n.d.k_ 形式)
|tableName |表の標題
|subTableName |表の副題
|noteID |注釈番号(CodeFlag_notes.csvを参照)
|notation |注記表示
|===

表版号tableNo列は、
CSVファイル名に分野番号__d__やカテゴリ番号__k__を欠く表については
たとえば符号表1.2であれば「1.2.0.0」のようにゼロを補う。
符号表4.2については「4.2.0.1」のように非零数が入る。
不規則なのは符号表4.1で、CSVファイルは一体だが、
本表では分野番号__d__ごとにエントリが建てられている。
通報式の文書では符号表4.1は__d__毎に、
符号表4.2は__(d,k)__毎に表が分けられそれぞれに注がついている。

表の標題と副題について重複した情報源がある。
どちらを採るべきかと考えるとき、
notes/CodeFlag_table.csvのエントリと
表本体のCSVファイルのリストを比較すると、
現時点では表本体のCSVがあって
notes/CodeFlag_table.csvのエントリが欠けている表があるので、
各表本体のTitle_en,SubTitle_en欄を用いるしかない。

=== GRIB2テンプレート
* `GRIB2/GRIB2_Template{usc}1`{usc}__t__{usc}``IdentificationTemplate_en.csv`` - 識別テンプレート1.__t__
* `GRIB2/GRIB2_Template{usc}3`{usc}__t__{usc}``GridDefinitionTemplate_en.csv`` - 格子系定義テンプレート3.__t__
* `GRIB2/GRIB2_Template_4`{usc}__t__{usc}``ProductDefinitionTemplate_en.csv`` - プロダクト定義テンプレート4.__t__
* `GRIB2/GRIB2_Template_5`{usc}__t__{usc}``DataRepresentationTemplate_en.csv`` - 資料表現テンプレート5.__t__
* `GRIB2/GRIB2_Template_7`{usc}__t__{usc}``DataTemplate_en.csv`` - 資料テンプレート7.__t__
* `GRIB2/notes/Template_notes.csv` - 注釈番号から注釈文を与える
* `GRIB2/notes/Template_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでテンプレート番号 _t_ = 0..65535 である。

テンプレート本体は次のフィールドを持つ:

|===
|列名 |名称・用法 
|Title_en |表の標題(全行共通)
|OctetNo | オクテット番号(複数ならばハイフンで範囲を示す)
|OctetCount | オクテット数
|Contents_en | 内容
|Note_en |注記表示(非空白の場合、意味に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,CodeFlag_notes.csvを参照)
|codeTable | 注記が符号表を参照する場合の符号表番号
|flagTable | 注記がフラグ表を参照する場合のフラグ表番号
|Status | 状態
|===

Title_enは表の冒頭に表示する文字列であり、
noteIDs, codeTable, flagTable は表示テキストではなくリンクを指示する。
<<Status,Statusは表示に反映しない(後述)>>ので、
結局OctetNo, OctetCount, Contents_en, Note_en が表示されることになる。

テンプレートはTDCFでいう表の一部だが、
行の順序に意味があって入れ替えはできないので、
コッドの正規形の表ではない。
しかしながら、OctetNo列は単調増加するので、
区別できない行が複数登場することはない。
加えて、テンプレートは実装上の負担が大きいので、
運用開始後に訂正ではない一部変更は想定しなくていいだろう。

=== BUFR/CREX符号表

* `BUFR4/BUFRCREX_CodeFlag_en`{usc}__xx__``.csv`` - 符号・フラグ表第 _xx_ クラス
* `BUFR4/notes/BUFRCREX_CodeFlag_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFRCREX_CodeFlag_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでクラス番号 _xx_ = 00..63 である。

=== BUFR/CREX表A

* `BUFR4/BUFR_TableA_en.csv` - BUFR表A本体
* `BUFR4/CREX_TableA_en.csv` - CREX表A本体

表Aに注釈ファイルはない。

=== BUFR/CREX表B

* `BUFR4/BUFRCREX_TableB_en`{usc}__xx__``.csv`` - BUFR/CREX表B第 _xx_ クラス
* `BUFR4/notes/BUFRCREX_TableB_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFRCREX_TableB_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでクラス番号 _xx_ = 00..63 である。

=== BUFR/CREX表C

* `BUFR4/BUFR_TableC_en.csv` - BUFR表C本体
* `BUFR4/CREX_TableC_en.csv` - CREX表C本体
* `BUFR4/notes/BUFR_TableC_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFR_TableC_table.csv` - 表のエントリではなく表全体にかかる注を記載

CREX表Cの注釈文情報は欠けている。それどころかCREX表Cに注釈番号列noteIDsが欠けている。

=== BUFR/CREX表D

* `BUFR4/BUFR_TableD_en`{usc}__xx__``.csv`` - BUFR表D第 _xx_ クラス
* `BUFR4/CREX_TableD_en`{usc}__xx__``.csv`` - CREX表D第 _xx_ クラス
* `BUFR4/notes/BUFR_TableD_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFR_TableD_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでクラス番号 _xx_ = 00..63 である。
CREX表Dの注釈文情報は欠けている。それどころかCREX表Dに注釈番号列noteIDsが欠けている。

=== 共通符号表

* `CCT/COV.csv` - 共通符号表一覧
* `CCT/C`__cc__``.csv`` - 共通符号表 C-_cc_
* `CCT/notes/CCT_notes.csv` - 注釈番号から注釈文を与える
* `CCT/notes/CCT_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここで表番号 _cc_ = 00,01,...,08,11,...,14 である。
共通符号表は _cc_ により列構造が異なる。

== 共通の特殊列処理

[[Status]]
=== Status列の扱い

多くの表にStatus列がある。その意味は次のとおり

* Operational - 現用の通報式
* Deprecated - 現用の通報式だが、廃止予定と宣言
* Experimental - 通報式には掲載するが、バリデーションが未了との注記を付す
* Extension - CCT C-14 で使われる。現用通報式には掲載されていない。

なお、次の品質的問題がある。

* 一部空欄になっている場合がある。
  CCT C-06 では Operational と解せばよいが
  GRIB2テンプレート3.1000 は Experimental とすべきだろう。
  機械的解釈を避けて脱字として処理すべき。
* Operational は様々な typo がある（Oprational, Operatonal,
  Operationaal など、また前後にスペース付加も)

処理としては、 Deprecated のある行に注記を付加し、
Extension のある行を削除するのだろう。
