= TDCF通報式のWMOが提供するCSV表の処理
:scripts: cjk
:author: TOYODA Eizi
:sectnums:
:toc:
:usc: _

== 予備知識

=== TDCF表のあらまし

WMO通報式のうち、FM92 GRIB、FM94 BUFR、FM95 CREXは
表参照通報式(table-driven code forms)と総称されている。
これらの通報式の大部分はTDCF表と呼ばれる表となっていて、
運用に影響しない改正（表への追記や非本質的な訂正など）が
迅速に行えるよう、
ファストトラック改正手続きが認められている。
TDCF表はGitHubで公開されている。

FM92 GRIB通報式第2版(通称GRIB2)によるGRIB報は、
第0節から第8節までの9個の節(section)から構成される。
このうち第1,3,4,5,及び7節は
テンプレート番号(0..65535)によって異なる構造を持つ。
各節は1オクテットから4オクテットの数値の羅列として定義されるが、
オクテットの数値を整数または浮動小数点数として用いる場合の他に、
整数値で符号表(code table)に列挙された語彙として用いる場合と、
整数値をビット列に分解してフラグをあてはめる場合がある。

GRIB2においてはテンプレート及び符号表・フラグ表がTDCF表である。

FM94 BUFR通報式第4版(通称BUFR4)および
FM95 CREX通報式は、
BUFR報またはCREX報の冒頭に置かれる記述子(descriptor)の羅列で
後に続くデータの構造を指定する。
記述子は16ビットで _F, X, Y_ の3部分に分解され、
それぞれ2,6,8ビットを占めてそれぞれ十進表記される。
_F_=0 すなわち 0 _XX YYY_ の形をとる記述子は要素記述子と呼ばれ、
データの名称、単位、占有ビット数を記載したBUFR/CREX表Bで定義される。
要素記述子のクラス番号 _XX_ の表はBUFR/CREX表Aである。
_F_=2 すなわち 2 _XX YYY_ の形をとる記述子は操作記述子と呼ばれ、
記述子列の解釈に特別な影響を与える操作(operation)を表現し、
BUFR/CREX表Cで定義される。
_F_=3 すなわち 3 _XX YYY_ の形をとる記述子は集約記述子と呼ばれ、
複数の記述子をひとまとめに記述する簡略記法であって、
BUFR/CREX表Dで定義される。

要素記述子は原則として単位を持った物理量を表現するが、
符号表に列挙される語彙を参照する場合や、
フラグ表に示されるビットの組み合わせを表現する場合があり、
これらはBUFR/CREXの符号・フラグ表で定義される。

BUFR/CREXにおいては表A-D及び符号・フラグ表がTDCF表である。

これらの他に、複数のWMO通報式で共通に参照する表が
共通符号表(common code table)として定義されている。

=== 以下で用いる記号

[cols="1,2,5",options="header"]
|===
|記号 |範囲 |意味 
|_cc_ |0以上（現在14まで使用） |共通符号表番号
|_d_ |0-255 |GRIB2符号表4.2で用いる分野(discipline)番号
|_F_ |0-3 |BUFR/CREX の記述子の _F_ 部、十進表現1桁
|_FXY_ | |BUFR/CREXの記述子の _F,X,Y_ 部を十進表現1,2,3桁で並べたもの
|_k_ |0-255 |GRIB2符号表4.2で用いるカテゴリ(category)番号
|_n_ |0以上 (現在336まで使用) |GRIB2の符号・フラグ表の番号
|_s_ |1,3,4,5,7 |GRIB2の節(section)番号
|_s.n.d.k_ | |GRIB2の符号表を識別する番号 _s,n,d,k_ (欠はゼロで補う)をピリオド区切りで並べたもの
|_t_ |0-65535 |GRIB2のテンプレート番号
|_XX_ |0-63 |BUFR/CREX の記述子の _X_ 部 (要素記述子ではクラス(class)番号という)、十進表現2桁ゼロ前置
|_YYY_ |0-255 |BUFR/CREX の記述子の _Y_ 部、十進表現3桁ゼロ前置
|===

GRIB2最大の符号表4.2はパラメタ(parameter)番号であるが、
パラメタの数が多いため、
それぞれ8ビットの分野(discipline)、カテゴリ(category)、
及びパラメタの3つの番号でパラメタが識別される。

== WMO CSVのファイル構造
=== レポジトリ
次の3つのレポジトリに分かれて管理されている:

* https://github.com/wmo-im/GRIB2
* https://github.com/wmo-im/BUFR4 (CREXを含む)
* https://github.com/wmo-im/CCT

==== ブランチの使い方

* `main` - 現行最新通報式
* `FT2026-1` - 照会中ファストトラック
* `FT2025-2` (削除済み) - 前回のファストトラック

[[GCF]]
=== GRIB2符号表

GRIB2 の符号表(code table) は次のCSVに格納されている:

* `GRIB2/GRIB2_CodeFlag`{usc}__s{usc}n__``{usc}CodeTable{usc}en.csv`` - 符号表__s__._n_
* `GRIB2/GRIB2_CodeFlag`{usc}__s{usc}n__``{usc}FlagTable{usc}en.csv`` - フラグ表__s__._n_
* `GRIB2/GRIB2_CodeFlag`{usc}4{usc}2{usc}__d{usc}k__``{usc}CodeTable{usc}en.csv`` - 符号表4.2のファイル名
* `GRIB2/notes/CodeFlag_notes.csv` - 注釈番号から注釈文を与える
* `GRIB2/notes/CodeFlag_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここで節(section)番号 _s_ = 1,3,4,5,7; 表番号 _n_ = 0以上の整数(現行規定は336まで使用); 分野(discipline)番号 _d_ = 0..255 (符号表0.0); カテゴリ番号 _k_ = 0..255 (符号表4.1)である。

[[GCFcsv]]
==== CSVの構造

符号表は次のフィールドを持つ:

|===
|列名 |名称・用法
|Title_en |表の標題(全行同一)
|SubTitle_en |表の副題(全行同一、符号表4.1及び4.2で非空白)
|CodeFlag |「数字符号」またはフラグ表の場合は「ビット」
|Value |「値」。フラグ表で非空白
|MeaningParameterDescription_en |意味
|Note_en |注記表示(非空白の場合、前列に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,CodeFlag_notes.csvを参照)
|UnitComments_en |「単位」。符号表4.2で使用
|Status |状態
|===

全行同一のTitle_en, SubTitle_en は表の上枠外に表示されるもので、
Statusは表示に反映しない<<Status,(後述)>>。
結局、CodeFlag, Value, およびMeaningParameterDescription_en
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結)
の3個列が通報式の文書に  
書かれる。

[[GCFNN]]
==== 注釈CSVの構造

notes/CodeFlag_notes.csv は次のフィールドを持つ:

|===
|列名 |名称・用法
|noteID |注釈番号(表本体から参照するキー)
|note |注釈文字列
|===

[[GCFNT]]
==== 表注釈CSVの構造
notes/CodeFlag_table.csv は次のフィールドを持つ:

|===
|列名 |名称・用法
|tableNo |表番号(_s.n.d.k_ 形式)
|tableName |表の標題
|subTableName |表の副題
|noteID |注釈番号(CodeFlag_notes.csvを参照)
|notation |注記表示
|===

表版号tableNo列では、CSVファイル名に分野(discipline)番号 _d_ やカテゴリ番号 _k_ を欠く場合ゼロを  
補う。  
たとえば符号表1.2であれば「1.2.0.0」となる。
符号表4.2については「4.2.0.1」のように  
非零数が  
入る。
不規則なのは符号表4.1である: 表本体のCSVファイルは1つしかないが、
CodeFlag_table.csvには分野番号 _d_ ごとに別の行が与えられている。
通報式(WMO Codes)の文書では、  
符号表4.1は _d_ 毎に別の表、符号表4.2は _(d,k)_ 毎に
別の表が組版されており、それぞれに注がついて
いる。

本表と表本体を比較すると、
本表に一部の _s.n.d.k_ 値を記述する行が欠けているので、
本表は注釈番号を解釈する
ためだけに用いるべきである。

本表では同一のtableNoの行が複数あることに注意。
GRIB符号・フラグ表 _s.n.d.k_ を出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[GT]]
=== GRIB2テンプレート
* `GRIB2/GRIB2_Template{usc}1`{usc}__t__{usc}``IdentificationTemplate_en.csv`` - 識別テンプレート1.__t__
* `GRIB2/GRIB2_Template{usc}3`{usc}__t__{usc}``GridDefinitionTemplate_en.csv`` - 格子系定義テンプレート3.__t__
* `GRIB2/GRIB2_Template_4`{usc}__t__{usc}``ProductDefinitionTemplate_en.csv`` - プロダクト定義テンプレート4.__t__
* `GRIB2/GRIB2_Template_5`{usc}__t__{usc}``DataRepresentationTemplate_en.csv`` - 資料表現テンプレート5.__t__
* `GRIB2/GRIB2_Template_7`{usc}__t__{usc}``DataTemplate_en.csv`` - 資料テンプレート7.__t__
* `GRIB2/notes/Template_notes.csv` - 注釈番号から注釈文を与える
* `GRIB2/notes/Template_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでテンプレート番号 _t_ = 0..65535 である。

[[GTcsv]]
==== CSVの構造
テンプレート本体は次のフィールドを持つ:

|===
|列名 |名称・用法 
|Title_en |表の標題(全行同一)
|OctetNo | オクテット番号(複数ならばハイフンで範囲を示す)
|OctetCount | オクテット数
|Contents_en | 内容
|Note_en |注記表示(非空白の場合、前列に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,Template_notes.csvを参照)
|codeTable | 注記が符号表を参照する場合の符号表番号
|flagTable | 注記がフラグ表を参照する場合のフラグ表番号
|Status | 状態
|===

Title_enは表の冒頭に表示する文字列であり、  
noteIDs, codeTable, flagTable は表示されずリンクを  
指示する。
Statusは表示に反映しない<<Status,(後述)>>。
結局 OctetNo, OctetCount, Contents_en
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結)
の3列が
表示されることになる。

テンプレートは関係データベースの関係(relation)とみなすことはできない。
行の順序に意味があるから  
である。
しかしながら、OctetNo列は行の順序に沿って単調増加するので、
テンプレートの
一部だけが
差分として表示されたとしても、変更の位置が判読不能となることはない。

[[GTNN]]
==== 注釈CSVの構造
`GRIB2/notes/Template_notes.csv` は<<GCFNN,GRIB2符号表の注釈CSV>>と同様。

[[GTNT]]
==== 表注釈CSVの構造
`GRIB2/notes/Template_table.csv` は次の構造を持つ:

|===
|列名 |名称・用法 
|templateNo | テンプレート番号（__s.t__形式）
|templateName | テンプレート標題
|noteID |注釈番号(Template_notes.csvを参照)
|notation |注記表示番号
|===

列templateNoは「3.0」「4.6」などの _s.t_ 形式の文字列である。

本表と表本体を比較すると、
本表に一部の _s.t_ 値を表わす行が欠けているので、
本表は注釈番号を
解釈するため
だけに用いるべきである。

本表では同一のtemplateNoの行が複数あることに注意。
GRIBテンプレート _s.t_ を出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[BCF]]
=== BUFR/CREX符号表

* `BUFR4/BUFRCREX_CodeFlag_en`{usc}__XX__``.csv`` - 符号・フラグ表第 _XX_ クラス
* `BUFR4/notes/BUFRCREX_CodeFlag_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFRCREX_CodeFlag_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでクラス番号 _XX_ = 00..63 である。

[[BCFcsv]]
==== CSVの構造

符号・フラグ表本体は次の列を持つ:

|===
|列名 |名称・用法 
|FXY | 表参照符(要素を識別するキー)
|ElementName_en | 要素名
|CodeFigure | 「数字符号」またはフラグ表の場合は「ビット」
|EntryName_en | 値の意味
|EntryName_sub1_en | 値の意味の補足1
|EntryName_sub2_en | 値の意味の補足2
|Note_en |注記表示(非空白の場合、値の意味に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,Template_notes.csvを参照)
|Status | 状態
|===

BUFR/CREXの符号・フラグ表は、単一のCSVファイルに多数の表が詰め込まれている。
FXY及び  
ElementName_en列が同じ行が複数並んでいて、これが1つの表である。
FXY列が異なる行は別の表に
属する。
ElemetName_en列は表の標題として用いる
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結)。
Statusは表示に反映しない<<Status,(後述)>>。

EntryName_sub1_en及びEntryName_sub2_en列はさまざまな使い方がされる:

* 0 08 043 (化学的または物理的成分の種類) ではEntryName_sub1_en及び  
  EntryName_sub2_enが化学式及びCAS番号を補足的に与える
* 0 20 003 (現在天気) ではEntryName_enが大分類（複数の行で同じ値）で
  通報式文書では複数行をカッコで結んで表示され、
  EntryName_sub1_enが
  小分類となっている
* 0 20 034 (海氷の密度) ではEntryName_sub1_enが中分類、
  EntryName_sub2_enが大分類で、
  通報式文書ではそれぞれ複数行をカッコで結んで表示される

これらすべての視覚的表示方法を再現することは高コストなので、EntryName_sub1_en及びEntryName_sub2_enを括弧書きしてEntryName_enに書き加えるのが現実的と思われる。

[[BCFNN]]
==== 注釈CSVの構造
`BUFR4/notes/BUFRCREX_CodeFlag_notes.csv` の構造は
<<GCFNN,GRIB2符号表の注釈CSV>>と同様。

[[BCFNT]]
==== 表注釈CSVの構造
`BUFR4/notes/BUFRCREX_CodeFlag_table.csv` は次の列を持つ:

|===
|列名 |名称・用法 
|tableNo |表番号( _F XX YYY_ 形式)
|tableName |表の標題
|noteID |注釈番号(BUFRCREX_CodeFlag_notes.csvを参照)
|notation |注記表示
|===

本表のtableNo列からスペースを除いたものは基本的に、
表本体のFXY列に対応する。
たとえば本表で 0 01 003 とある行は表本体の 001003 に対応する。
本表と表本体を比較すると、
本表に一部の _FXY_ 値が
欠けているので、
本表は注釈番号を解釈するため
だけ
に用いるべきである。

本表では 0 20 004/0 20 005 および 0 23 008/0 23 009 については
1行で2個の要素記述子を記載して
いるが、
これらの要素記述子には表全体への注釈がついていないので、
注釈番号を解釈するため
だけに本表を用いるならば
スラッシュ区切り構文を処理しなくても問題ない。

本表では同一のtableNoの行が複数あることに注意。
BUFR/CREX符号・フラグ表のうち、記述子 _F XX YYY_ の表を出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[BCA]]
=== BUFR/CREX表A

* `BUFR4/BUFR_TableA_en.csv` - BUFR表A本体
* `BUFR4/CREX_TableA_en.csv` - CREX表A本体

表Aに注釈ファイルはない。

[[BCAcsv]]
==== CSVの構造

BUFR表A本体およびCREX表A本体は次の列を持つ:

|===
|列名 |名称・用法 
|CodeFigure | 数字符号(0-255)
|Meaning_en | 意味
|Status | 状態
|===

数字符号は表Bのクラスである。原則として数値ひとつだが、
102-239 及び 240-254 は範囲表記で
書かれている。
Statusは表示に反映しない<<Status,(後述)>>。

CREX表A/Bにはクラス14,15,32を欠くので2つの表は別になっている。

[[BCB]]
=== BUFR/CREX表B

* `BUFR4/BUFRCREX_TableB_en`{usc}__XX__``.csv`` - BUFR/CREX表B第 _XX_ クラス
* `BUFR4/notes/BUFRCREX_TableB_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFRCREX_TableB_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでクラス番号 _XX_ = 00..63 である。

[[BCBcsv]]
==== CSVの構造

BUFR/CREX表BのCSVは長すぎるのでクラス番号 _XX_ によって分割されている。
各CSVは次の列を持つ:

|===
|列名 |名称・用法 
|ClassNo | クラス番号 _XX_
|ClassName_en | クラス名称
|FXY | 表参照符 _FXY_
|ElementName_en | 要素名
|BUFR_Unit | BUFRの単位
|BUFR_Scale | BUFRの尺度
|BUFR_ReferenceValue | BUFRの参照値
|BUFR_DataWidth_Bits | BUFRのビット幅
|CREX_Unit | CREXの単位
|CREX_Scale | CREXの尺度
|CREX_DataWidth_Char | CREXの文字数
|Note_en |注記表示(非空白の場合、要素名に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,BUFRCREX_CodeFlag_notes.csvを参照)
|Status |状態
|===

ClassNo および ClassName_en 列はクラス内で全行同一である。
クラスごとに分割表示する際に題字として用いる。
Statusは表示に反映しない<<Status,(後述)>>。
通報式文書の表では
FXY, ElementName_en
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結)
に続いて BUFR_Unit から CREX_DataWidth_Char 列までが表示される。

[[BCBNN]]
==== 注釈CSVの構造

`BUFR4/notes/BUFRCREX_TableB_notes.csv` の構造は
<<GCFNN,GRIB2符号表の注釈CSV>>と同様。

[[BCBNT]]
==== 表注釈CSVの構造

`BUFR4/notes/BUFRCREX_TableB_table.csv` は次の列を持つ:

|===
|列名 |名称・用法 
|tableNo |表番号(クラス番号 _XX_ )
|tableName |表の標題
|noteID |注釈番号(BUFRCREX_TableB_notes.csvを参照)
|notation |注記表示
|===

本表では同一のtableNoの行が複数あることに注意。
BUFR/CREX表Bのうち、クラス _XX_ の表を出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

//HEAD
=== BUFR/CREX表C

* `BUFR4/BUFR_TableC_en.csv` - BUFR表C本体
* `BUFR4/CREX_TableC_en.csv` - CREX表C本体
* `BUFR4/notes/BUFR_TableC_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFR_TableC_table.csv` - 表のエントリではなく表全体にかかる注を記載

CREX表Cの注釈文情報は欠けている。それどころかCREX表Cに注釈番号列noteIDsが欠けている。

==== CSVの構造
==== 注釈CSVの構造
==== 表注釈CSVの構造

=== BUFR/CREX表D

* `BUFR4/BUFR_TableD_en`{usc}__XX__``.csv`` - BUFR表D第 _XX_ クラス
* `BUFR4/CREX_TableD_en`{usc}__XX__``.csv`` - CREX表D第 _XX_ クラス
* `BUFR4/notes/BUFR_TableD_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFR_TableD_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでクラス番号 _XX_ = 00..63 である。
CREX表Dの注釈文情報は欠けている。それどころかCREX表Dに注釈番号列noteIDsが欠けている。

==== CSVの構造
==== 注釈CSVの構造
==== 表注釈CSVの構造

=== 共通符号表

* `CCT/COV.csv` - 共通符号表一覧
* ``CCT/C``__cc__``.csv`` - 共通符号表 C-_cc_
* `CCT/notes/CCT_notes.csv` - 注釈番号から注釈文を与える
* `CCT/notes/CCT_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここで表番号 _cc_ = 00,01,...,08,11,...,14 である。
共通符号表は _cc_ により列構造が異なる。

==== CSVの構造
==== 注釈CSVの構造
==== 表注釈CSVの構造

== 共通の特殊列処理

[[Status]]
=== Status列の扱い

多くの表にStatus列がある。その意味は次のとおり

* Operational - 現用の通報式
* Deprecated - 現用の通報式だが、廃止予定と宣言
* Experimental - 通報式には掲載するが、バリデーションが未了との注記を付す
* Extension - CCT C-14 で使われる。現用通報式には掲載されていない行。

なお、次の品質的問題がある。

* 一部空欄になっている場合がある。
  CCT C-06 では Operational と解せばよいが
  GRIB2テンプレート3.1000 は Experimental とすべきだろう。
  機械的解釈を避けて脱字として処理すべき。
* Operational は様々な typo がある（Oprational, Operatonal,
  Operationaal など、また前後にスペース付加も)

処理としては、 Deprecated のある行に注記を付加し、
Extension のある行を削除するのが妥当と推定。

TODO: Deprecatedの用例について通報式文書を確認し、注記付加処理でよいか確認

[[parsingNotes]]
=== 注釈の扱い

TBD
