= WMO GithubのTDCF表による自動差分作成処理
:scripts: cjk
:author: TOYODA Eizi
:date: 2026-02-27
:sectnums:
:toc:
:usc: _
:mdash: &#x2014;
:kuhaku: &#x2423;

== はじめに

WMO通報式のうち、FM92 GRIB、FM94 BUFR、FM95 CREXは
表参照通報式(table-driven code forms)と総称されている。
これらの通報式の大部分はTDCF表と呼ばれる表となっていて、
運用に影響しない改正（表への追記や非本質的な訂正）が
迅速に行えるよう、
会議によらないファストトラック改正手続きが認められている。
ただし、CREX通報式はBUFRへの移行進展に伴い2024年に改正が凍結された (Rec.8 INFCOM-3, Res. 17 EC-78)。
TDCF表はGithubで公開されている。

WMOにおけるファストトラック改正のたびに迅速に改正内容を把握周知するために、
新旧Githubから複数の版のTDCF表を取得して差分ドキュメントを自動作成することを考える。

=== TDCF表概説

通報式の体系について述べる。

GRIB通報式第2版(通称GRIB2)によるGRIB報は、
第0節から第8節までの9個の節(section)から構成される。
このうち第1,3,4,5,及び7節は
**テンプレート**番号によって異なる構造を持つ。
各節は1オクテットから4オクテットの数値の羅列として定義されるが、
オクテットの数値を整数または浮動小数点数として用いる場合の他に、
整数値で**符号表**(code table)に列挙された語彙として用いる場合と、
**フラグ表**(flag table)に従い整数値をビット列に分解して真偽値を示す場合がある。

GRIB2においてはテンプレート及び符号表・フラグ表がTDCF表である。
テンプレートは _s.t_ の形の番号で、符号表・フラグ表は _s.n_ の形の番号で識別される。
ここで _s_=1,3,4,5,7; _t_=0..65535; __n__は0以上の整数である。

BUFR/CREX 通報式では、報文に記述されるデータの構造を「記述子」と呼ばれる整数の列で定義する。
この記述子の体系は次の 表A〜D の4種類の表で定義されている。
まず *表A* は、データ要素を大まかな分類（気温、風、放射、海洋など）に分けるための「クラス一覧」である。
次に *表B* は、実際の観測・予報資料の要素を定義する「要素記述子」を定義する表で、
クラス毎に各要素の名称、単位、尺度、ビット幅といった属性を規定する。
*表C* は、データの読み取りに特別な操作を加えるための表で、記述子列の意味や解釈方法を変える各種の「操作記述子」を定義する。
表Bに定める要素だけでは表現できない数値の範囲拡大や付加的な情報などが表現される。
最後に *表D* は、よく使われる記述子列を1つで表現する「集約記述子」を定義する。

具体的には記述子は16ビットで、__F__(2ビット)、__X__(6ビット)、__Y__(8ビット)の3部分に分解され、
__F__の値が0,2および3の場合がそれぞれ要素記述子、操作記述子、および集約記述子にあたる。
要素記述子については表Aと表Bが__X__及び__Y__を定義する。

要素記述子は原則として単位を持った物理量を表現するが、
符号表に列挙される語彙を参照する場合や、
フラグ表に示されるビットの組み合わせを表現する場合があり、
これらはBUFR/CREXの *符号・フラグ表* で定義される。

BUFR/CREXにおいては表A-D及び符号・フラグ表がTDCF表である。
符号・フラグ表は要素記述子 _FXY_ で識別される。

これらの他に、GRIB、BUFR/CREX、およびTAC通報式で共通に参照する表が
共通符号表(common code table)として定義されている。
共通符号表はC00からC14までの番号__cc__で識別される（09及び10は現状欠番）。

[[SAIBUN]]
==== 表の細分

通報式の規則で番号がついて識別される表を、以下本文書では**論理表**（logical table）と呼ぶことにする。

上記の表に、注がついている。
注は表の各行につけられるものと、表全体につけられるものがある。
行に対する注と表全体に対する注が共通の番号体系をもっていて、
表の下に番号順に表示される。
一部の表では、論理表を適宜に分割して、その後に注を列挙する。
WMO GitHubのCSVデータは一次細分単位で編成されている。
以下本文書ではこれを**一次細分**(first level subdivision)と呼ぶ。
たとえばGRIB2最大の符号表4.2はパラメタ(parameter)番号であるが、
パラメタの数が多いため、
それぞれ8ビットの分野(discipline)、カテゴリ(category)、
及びパラメタの3つの番号でパラメタが識別される。
符号表4.2の一次細分は分野とカテゴリで分割している。

なお、通報式文書を見ると、注記には
表の各行につけられたもの、表全体につけられたものの他に、
節見出しの直下についているものがあり、これはCSVデータでは提供されていない。
少なくとも符号表4.2冒頭にはそれがある。
これらは昔から変わらない原則なので改正は見込まれないため、差分を作るときは無視してよい。
いっぽうで、通報式の文書を生成するときは考慮が必要である。

**TODO** 節見出し直下の注を列挙網羅すること。

（WMO Manual on Codes 及び日本の「国際気象通報式 別冊」)で
印刷上分割されている。
以下本文書ではこれを**二次細分**(second level subdivision) と呼ぶ。


[cols="3,1,5,2,3",option="header"]
|===
|論理表の種類 |論理表の識別 |論理表の分割 |差分注意 |補足
|GRIBテンプレート |_s.t_ |非分割 |順序型 |__s__毎に節見出し
|GRIB符号・フラグ表 |__s.n__ |非分割 |{mdash} |
|うち GRIB符号表4.1 |__s.n__=4.1 |非分割 |{mdash} | 
|うち GRIB符号表4.2 |_s.n_=4.2 |(一次細分・二次細分ともに)__d.k__毎に分割 |{mdash} |冒頭注データを欠く
|BUFR表A |{mdash} |非分割 |{mdash} |注記なし
|BUFR/CREX表B |{mdash} |(一次細分・二次細分ともに)__XX__毎に分割 |{mdash} | 
|BUFR表C |{mdash} |非分割 |{mdash} |
|BUFR表D |{mdash} |一次細分:__XX__毎に分割、二次細分:__FXY__毎に分割 |順序型、一意キーなし |
|BUFR/CREX符号・フラグ表 |{mdash} |一次細分:__XX__毎に分割、二次細分:__FXY__毎に分割 |{mdash} |
|CREX表A |{mdash} |非分割 |{mdash} |注記なし
|CREX表C |{mdash} |非分割 |{mdash} |注釈データを欠く
|CREX表D |{mdash} |一次細分:__XX__毎に分割、二次細分:__FXY__毎に分割 |順序型、一意キーなし |注釈データを欠く
|共通符号表 |_cc_ |非分割 |{mdash} |
|うち 共通符号表C06 |_cc_=06 |一次細分:非分割; 二次細分:UnitType毎に分割 |{mdash} |
|===

* 「論理表の識別」列に記載があるものは同一種類で複数の論理表があるときの識別番号フォーマット。記号は<<SYMBOLS>>参照。
* 「差分注意」列で「順序型」とした表は、行の順番に意味があり、行を並び替えると意味をなさない。関係データベースとは異なる。
  特にBUFR/CREX表Dは全く同一内容の行が複数現れ得るので、行単位の差分を表示しても意味をなさない危険がある。
  この表に限り、行単位の変化を二次細分の加除の形で表現する必要がある。
* GRIB符号表4.2は、二次細分毎につけられた注釈と別に、符号表4.2の見出しの直下に注があるが、
  CSVデータでは提供されていない。他の注釈と構造が違う上に、改正が見込まれないからであろう。
* BUFR/CREX表Aには注釈がついていない。
* CREX表C及び表Dは、注釈がついているが、表の下に記載すべき注釈文がCSVデータで提供されていない。改正が見込まれないからであろう。

== 差分作成処理
[[Processing]]
=== 処理の概要

通報式の改正手続きに際して動かすことが想定される、差分作成処理は、次の3フェーズから構成される:

. データ収集と正規化
. 変化点の抽出
. 差分ドキュメント生成

より具体的には

. 新旧データセットそれぞれについて:
.. CSVファイルを探索して、論理表のリストとデータ構造を構築する
.. すべての表について
... <<Status,Status列>>に従い不要な行を除去する
... WMOの誤記のパッチをあてる
... 日本語訳のパッチをあてる
... 日本ローカル定義エントリを追加する
. 新旧データセットの間で同名の表の有無を比較して差分ドキュメントを作る
.. 表の加除があれば、表全体を表示する
.. 表に対する行の加除変更があれば、差分を表示する
... ただしBUFR/CREX表Dの変更は、二次細分表の加除の形で表現する
.. 注記の加除変更があれば、注記の差分を表示する

説明としては「差分抽出 → 差分ドキュメント生成」のほうが
明確かもしれないが、
本件処理は差分の論理的データ構造の全体を必要とする処理がなく、
論理表毎に作った差分ドキュメント片を連結すれば足りるので、
データ構造を設計し保持するのは無駄である。

なおここでは、ドキュメントの論理構造が計算機の主記憶に収まる前提で、
早い段階でCSVファイルを読み込む方針で書いている。
WMO CSV データは現時点では 6 Mbyte の大きさであり、
新旧の論理構造は 100 Mbyte 程度と想定されるからである。

=== データ読み込みと一次細分表記号

CSVファイルを読み込んで得たオブジェクトは次の一次細分表記号で管理する。

// 試作品csv-compile.rb とは幾分異なる
[cols="3,3",option="header"]
|===
|論理表の種類 |一次細分表記号
|GRIBテンプレート |``G-T``__s-ttttt__
|GRIB符号表 |``G-CF``__s-nnnnn__``-Code``
|うち GRIB符号表4.2 |``G-CF4-00002-``__dd-kkkkk__
|GRIBフラグ表 |``G-CF``__s-nnnnn__``-Flag``
|BUFR表A |``B-A``
|BUFR/CREX表B |``B-B``__XX__
|BUFR表C |``B-C``
|BUFR表D |``B-D``__XX__
|BUFR/CREX符号・フラグ表 |``BC-CF``__XX__
|CREX表A |``C-A``
|CREX表C |``C-C``
|CREX表D |``C-D``__XX__
|共通符号表 |``CCT-C``__cc__
|===

GRIB, BUFR, CREX, 共通符号表のそれぞれに、
たとえば `/^G-/` にマッチする一次細分表を全部集めてきて
記号順にソートすれば文書順になるようになっている。

=== データ正規化

==== パッチのデータ構造

パッチデータは現状では次のような形式である。

* csvName に一致するファイル名について、
* keyField 列が値 keyValue を持つ行であって、
* targetField 列が値 ifMatch を持つ場合に限り、
* それを値 replace に置換する

```
csvName,keyField,keyValue,targetField,ifMatch,replace
GRIB2_Template_3_0_GridDefinitionTemplate_en.csv,OctetNo,51-54,noteIDs,,9
GRIB2_Template_3_150_GridDefinitionTemplate_en.csv,OctetNo,32-35,noteIDs,197a,166
Template_table.csv,templateNo,7.1,noteID,135,134
C06.csv,CodeFigure,060,conventional,˚C,°Ｃ
```

現状では WMO による誤記または asciidoctor-pdf とフリーのフォントでうまく扱えない文字の置換が挙げられているが、
原理的には同様にすればほとんどの日本語訳テキストを埋め込むことが可能である。

ただし、この形式は、特定の列により特定の行が一位に特定できることを前提としている。
<<SAIBUN>>で「順序型、一意キーなし」とされたBUFR/CREX Table Dについては指定条件で複数の同一行が引っかかる可能性はある。
しかしTable Dについては日本語訳があるとすれば ElementDescription_en 列に限られ、
同じ英語版テキストが複数現れるとして、日本語版テキストも同じだろうので、実用的には問題ないと考えられる。

==== 日本ローカル定義エントリのデータ構造

GRIB/BUFR/CREX の多くの符号表について、番号空間の上位数値が「局地的利用のために保留」とされている。
通常の値の範囲は、0-255の空間に対しては192-254、0-65535の空間に対しては32768-65534である。
// 例外: GRIB2 CT4.2.2.4 27-254,  CT4.215 251-254, CT4.2.20.4 191-254 ct4.2.20.5 191-254 
// 例外: GRIB2 CT4.120 63000-65534, CT4.240 49152-65534, CT4.243 32768-, CT5.0 49152-65534
// 例外: BUFR4 CT008043 201-254
実際に多くが日本で使われている。

BUFR/CREX Table B/D はクラス 48-63 の全体と、国際共用クラス 0-47 のエントリ __YYY__=192-254 が局地的利用のために保留されている。
把握する限り、日本では Table D の局地的定義をしていない。
Table B の局地的クラスは 60 （地面，地震，火山資料）あるのみである。
Table B の局地的エントリはクラス 01/02/04-08/11-14/19/20/22/25/26/27 にみられる。

また、GRIB2 ではテンプレートの表である符号表 1.0, 3.0 および 4.0 (予約空間は32768-65534) ならびに 5.0 (予約空間は49152-65534) が局地的使用であるため、第1/3/4/5/7節には局地的テンプレートが存在しうる。
日本の局所的テンプレートは第3節と第4節に定義されている。
そこから日本独自の符号表を参照しており、符号表 JMA3.0 などといった命名法になっている。

これらについての系統的命名法は後述する (**TODO**)。

データ形式は、既存の表をそのまま転用する。ただし、<<Status,Status列>>については、「国際共用表からの削除」「JMA追加」の印を処理せねばならない。
GRIB符号・フラグ表について、たとえば次のように削除・挿入が必要だからである。

国際定義:
[cols="4",option="header"]
|===
|番号 |パラメータ |単位 |説明
|192-254 |局地的利用のため保留 | | 
|===

JMA局所定義(例):
[cols="4",option="header"]
|===
|番号 |パラメータ |単位 |説明
|192-199 |局地的利用のため保留 | | 
|200 |JMA独自のパラメータ |単位 |補遺
|201-254 |局地的利用のため保留 | | 
|===

=== 差分のアルゴリズム

* 非表示列(定義?) は差分では無視すべきだが、
  おそらく改正もないので入れても差し支えないだろう
* lcs diff をかけて（あれば）前後行も入れる

=== 表示方法

==== 差分の種類と表示

* 表の追加: 次の表__tableName__を追加するとしてヘッダと全ての行を表示
* 表の削除: 次の表__tableName__を削除するとしてヘッダと全ての行を表示
  (Table D の二次細分表の一部の変更は
  二次細分表の削除と追加で表現するため内容を示したい)
* 行の追加・削除: 旧新の変更点 (直前直後の行を含む) を示す
* 注釈の追加・削除: 旧新の変更点を示す

==== 表レンダラの動作

* 基本的には入力CSVの列をすべて表示する。
* 全行同一の列は表見出しにくくりだす。
* Notes は NoteIDs と組み合わせてリンクテキストに変換し、
  各表で主要な列につける (TBD)
* この他に注釈的な列を連結で処理する

==== 列名データ

列名データは現状では resources.csv に格納している。
表の名前のデータと混在している。

|===
|列名 |名称・用法 
|Keyword |置換元キーワード
|lang |英語なら``en``、日本語なら``ja``
|Text |置換文字列
|===

[[parsingNotes]]
==== Notes の解析

行毎の注釈がついている表には Notes 列がある
(ただし共通符号表 C-06 のみ Note 列)。
Notes 列は `(see Notes 3 and 5)` のような人間可読な文字列で、
文書に表示すべきものである。
参照先は行毎の注、符号表、フラグ表、および共通符号表の組み合わせで、
Notes 文字列を解析することでリンクの種類と指示先が判明する。
ただし行毎の注については Notes からは注釈表示番号が得られ、
noteIDs (共通符号表 C-06 のみ NoteID) 列の数字列から注釈番号を得る。

現時点での暫定レンダラは Notes 列を次のように処理する。

. 空配列 `ret=[]` を作成してリンク付きテキストを保持する。
  `ret` の要素は2要素の配列であり、
  表示テキストとリンク先シンボルからなる。
  リンクではないテキストはリンク先シンボルをnilとする。
. 冒頭に次のいずれかがあれば削って `ret` に積む
  * `/^\(flags{kuhaku}-{kuhaku}see{kuhaku}/`
  * `/^{kuhaku}?\([Ss]ee{kuhaku}\t*/` {mdash} `(see{kuhaku}` に正規化
  * `/^\((?=[CN])/` {mdash} `(see{kuhaku}`  に正規化
. テキストが非空で残っている限り、先頭に次のいずれかがあれば削って処理
  * `/^{kuhaku}and{kuhaku}(?!\d)/`  {mdash} `{kuhaku}and{kuhaku}` に正規化
  * `/^Code{kuhaku}table{kuhaku}(\d)\.(\d+|PTN)/`
    {mdash} PTNの場合はリンク割愛
  * `/^Flag{kuhaku}table{kuhaku}(\d)\.(\d+)/`
  * `/^Common{kuhaku}Code{kuhaku}table{kuhaku}{kuhaku}?C[-\u{2013}](\d+)(?:{kuhaku}in{kuhaku}Part{kuhaku}C\/c\.)?/`
  * `/^[Nn]otes?{kuhaku}(\d+(?:,{kuhaku}\d+)*(?:{kuhaku}and{kuhaku}\d+)?)/`
    {mdash} 数字列をリンクに
  * `/^Note(?=\)|{kuhaku}and)/`
    {mdash} `Note` に正規化
  * `/^\){kuhaku}?/`
  * 上記いずれでもない先頭文字があれば例外、プログラム異常終了
. `ret` 配列を返す

ここで {kuhaku} はスペースである。

符号表番号の `4.PTN` という参照は、
プロダクト定義テンプレート4.53及び4.54でだけ
用いられる partiton table number である。
これを受ける符号表はテンプレートの構造上 4.0-4.255 に限られるが、
内容的に符号表4.236および4.238と思われる。

== WMO CSVのファイル構造
=== レポジトリ
次の3つのレポジトリに分かれて管理されている:

* https://github.com/wmo-im/GRIB2
* https://github.com/wmo-im/BUFR4 (CREXを含む)
* https://github.com/wmo-im/CCT

==== ブランチの使い方

* `main` - 現行最新通報式
* `FT2026-1` - 照会中ファストトラック
* `FT2025-2` (削除済み) - 前回のファストトラック

[[GCF]]
=== GRIB2符号表

GRIB2 の符号表(code table) は次のCSVに格納されている:

* `GRIB2/GRIB2_CodeFlag`{usc}__s{usc}n__``{usc}CodeTable{usc}en.csv`` - 符号表__s__._n_
* `GRIB2/GRIB2_CodeFlag`{usc}__s{usc}n__``{usc}FlagTable{usc}en.csv`` - フラグ表__s__._n_
* `GRIB2/GRIB2_CodeFlag`{usc}4{usc}2{usc}__d{usc}k__``{usc}CodeTable{usc}en.csv`` - 符号表4.2のファイル名
* `GRIB2/notes/CodeFlag_notes.csv` - 注釈番号から注釈文を与える
* `GRIB2/notes/CodeFlag_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここで節(section)番号 _s_ = 1,3,4,5,7; 表番号 _n_ = 0以上の整数(現行規定は336まで使用); 分野(discipline)番号 _d_ = 0..255 (符号表0.0); カテゴリ番号 _k_ = 0..255 (符号表4.1)である。

[[GCFcsv]]
==== CSVの構造

符号表は次のフィールドを持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法
|Title_en |表の標題(全行同一)
|SubTitle_en |表の副題(全行同一、符号表4.1及び4.2で非空白)
|CodeFlag |「数字符号」またはフラグ表の場合は「ビット」
|Value |「値」。フラグ表で非空白
|MeaningParameterDescription_en |意味
|Note_en |注記表示(非空白の場合、前列に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,CodeFlag_notes.csvを参照)
|UnitComments_en |「単位」。符号表4.2で使用
|Status |状態
|===

全行同一のTitle_en, SubTitle_en は表の上枠外に表示されるもので、
Statusは表示に反映しない<<Status,(後述)>>。
結局、CodeFlag, Value, およびMeaningParameterDescription_en
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結)
の3個列が通報式の文書に  
書かれる。

[[GCFNN]]
==== 注釈CSVの構造

notes/CodeFlag_notes.csv は次のフィールドを持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法
|noteID |注釈番号(表本体から参照するキー)
|note |注釈文字列
|===

[[GCFNT]]
==== 表注釈CSVの構造
notes/CodeFlag_table.csv は次のフィールドを持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法
|tableNo |表番号(_s.n.d.k_ 形式)
|tableName |表の標題
|subTableName |表の副題
|noteID |注釈番号(CodeFlag_notes.csvを参照)
|notation |注記表示
|===

表版号tableNo列では、CSVファイル名に分野(discipline)番号 _d_ やカテゴリ番号 _k_ を欠く場合ゼロを  
補う。  
たとえば符号表1.2であれば「1.2.0.0」となる。
符号表4.2については「4.2.0.1」のように  
非零数が  
入る。
不規則なのは符号表4.1である: 表本体のCSVファイルは1つしかないが、
CodeFlag_table.csvには分野番号 _d_ ごとに別の行が与えられている。
通報式(WMO Codes)の文書では、  
符号表4.1は _d_ 毎に別の表、符号表4.2は _(d,k)_ 毎に
別の表が組版されており、それぞれに注がついて
いる。

本表と表本体を比較すると、
本表に一部の _s.n.d.k_ 値を記述する行が欠けているので、
本表は注釈番号を解釈する
ためだけに用いるべきである。

本表では同一のtableNoの行が複数あることに注意。
GRIB符号・フラグ表 _s.n.d.k_ を出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[GT]]
=== GRIB2テンプレート
* `GRIB2/GRIB2_Template{usc}1`{usc}__t__{usc}``IdentificationTemplate_en.csv`` - 識別テンプレート1.__t__
* `GRIB2/GRIB2_Template{usc}3`{usc}__t__{usc}``GridDefinitionTemplate_en.csv`` - 格子系定義テンプレート3.__t__
* `GRIB2/GRIB2_Template_4`{usc}__t__{usc}``ProductDefinitionTemplate_en.csv`` - プロダクト定義テンプレート4.__t__
* `GRIB2/GRIB2_Template_5`{usc}__t__{usc}``DataRepresentationTemplate_en.csv`` - 資料表現テンプレート5.__t__
* `GRIB2/GRIB2_Template_7`{usc}__t__{usc}``DataTemplate_en.csv`` - 資料テンプレート7.__t__
* `GRIB2/notes/Template_notes.csv` - 注釈番号から注釈文を与える
* `GRIB2/notes/Template_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでテンプレート番号 _t_ = 0..65535 である。

[[GTcsv]]
==== CSVの構造
テンプレート本体は次のフィールドを持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|Title_en |表の標題(全行同一)
|OctetNo | オクテット番号(複数ならばハイフンで範囲を示す)
|OctetCount | オクテット数
|Contents_en | 内容
|Note_en |注記表示(非空白の場合、前列に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,Template_notes.csvを参照)
|codeTable | 注記が符号表を参照する場合の符号表番号
|flagTable | 注記がフラグ表を参照する場合のフラグ表番号
|Status | 状態
|===

Title_enは表の冒頭に表示する文字列であり、  
noteIDs, codeTable, flagTable は表示されずリンクを  
指示する。
Statusは表示に反映しない<<Status,(後述)>>。
結局 OctetNo, OctetCount, Contents_en
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結)
の3列が
表示されることになる。

テンプレートは関係データベースの関係(relation)と異なり、
行の順序に意味がある。
しかしながら、OctetNo列は行の順序に沿って単調増加するので、
テンプレートの一部だけが差分として表示されたとしても、
変更の位置が判読不能となることはない。

[[GTNN]]
==== 注釈CSVの構造
`GRIB2/notes/Template_notes.csv` は<<GCFNN,GRIB2符号表の注釈CSV>>と同様。

[[GTNT]]
==== 表注釈CSVの構造
`GRIB2/notes/Template_table.csv` は次の構造を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|templateNo | テンプレート番号（__s.t__形式）
|templateName | テンプレート標題
|noteID |注釈番号(Template_notes.csvを参照)
|notation |注記表示番号
|===

列templateNoは「3.0」「4.6」などの _s.t_ 形式の文字列である。

本表と表本体を比較すると、
本表に一部の _s.t_ 値を表わす行が欠けているので、
本表は注釈番号を
解釈するため
だけに用いるべきである。

本表では同一のtemplateNoの行が複数あることに注意。
GRIBテンプレート _s.t_ を出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[BCF]]
=== BUFR/CREX符号表

* `BUFR4/BUFRCREX_CodeFlag_en`{usc}__XX__``.csv`` - 符号・フラグ表第 _XX_ クラス
* `BUFR4/notes/BUFRCREX_CodeFlag_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFRCREX_CodeFlag_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでクラス番号 _XX_ = 00..63 である。

[[BCFcsv]]
==== CSVの構造

符号・フラグ表本体は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|FXY | 表参照符(要素を識別するキー、 _FXY_ 形式)
|ElementName_en | 要素名
|CodeFigure | 「数字符号」またはフラグ表の場合は「ビット」
|EntryName_en | 値の意味
|EntryName_sub1_en | 値の意味の補足1
|EntryName_sub2_en | 値の意味の補足2
|Note_en |注記表示(非空白の場合、値の意味に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,Template_notes.csvを参照)
|Status | 状態
|===

BUFR/CREXの符号・フラグ表は、単一のCSVファイルに多数の表が詰め込まれている。
FXY及び  
ElementName_en列が同じ行が複数並んでいて、これが1つの表である。
FXY列が異なる行は別の表に
属する。
ElemetName_en列は表の標題として用いる
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結)。
Statusは表示に反映しない<<Status,(後述)>>。

EntryName_sub1_en及びEntryName_sub2_en列はさまざまな使い方がされる:

* 0 08 043 (化学的または物理的成分の種類) ではEntryName_sub1_en及び  
  EntryName_sub2_enが化学式及びCAS番号を補足的に与える
* 0 20 003 (現在天気) ではEntryName_enが大分類（複数の行で同じ値）で
  通報式文書では複数行をカッコで結んで表示され、
  EntryName_sub1_enが
  小分類となっている
* 0 20 034 (海氷の密度) ではEntryName_sub1_enが中分類、
  EntryName_sub2_enが大分類で、
  通報式文書ではそれぞれ複数行をカッコで結んで表示される

これらすべての視覚的表示方法を再現することは高コストなので、EntryName_sub1_en及びEntryName_sub2_enを括弧書きしてEntryName_enに書き加えるのが現実的と思われる。

[[BCFNN]]
==== 注釈CSVの構造
`BUFR4/notes/BUFRCREX_CodeFlag_notes.csv` の構造は
<<GCFNN,GRIB2符号表の注釈CSV>>と同様。

[[BCFNT]]
==== 表注釈CSVの構造
`BUFR4/notes/BUFRCREX_CodeFlag_table.csv` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|tableNo |表番号( _F XX YYY_ 形式)
|tableName |表の標題
|noteID |注釈番号(BUFRCREX_CodeFlag_notes.csvを参照)
|notation |注記表示
|===

本表のtableNo列からスペースを除いたものは基本的に、
表本体のFXY列に対応する。
たとえば本表で 0 01 003 とある行は表本体の 001003 に対応する。
本表と表本体を比較すると、
本表に一部の _FXY_ 値が
欠けているので、
本表は注釈番号を解釈するため
だけ
に用いるべきである。

本表では 0 20 004/0 20 005 および 0 23 008/0 23 009 については
1行で2個の要素記述子を記載して
いるが、
これらの要素記述子には表全体への注釈がついていないので、
注釈番号を解釈するため
だけに本表を用いるならば
スラッシュ区切り構文を処理しなくても問題ない。

本表では同一のtableNoの行が複数あることに注意。
BUFR/CREX符号・フラグ表のうち、記述子 _F XX YYY_ の表を出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[BCA]]
=== BUFR/CREX表A

* `BUFR4/BUFR_TableA_en.csv` - BUFR表A本体
* `BUFR4/CREX_TableA_en.csv` - CREX表A本体

表Aに注釈ファイルはない。

[[BCAcsv]]
==== CSVの構造

BUFR表A本体およびCREX表A本体は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|CodeFigure | 数字符号(0-255)
|Meaning_en | 意味
|Status | 状態
|===

数字符号は表Bのクラスである。原則として数値ひとつだが、
102-239 及び 240-254 は範囲表記で
書かれている。
Statusは表示に反映しない<<Status,(後述)>>。

CREX表A/Bにはクラス14,15,32を欠くので2つの表は別になっている。

[[BCB]]
=== BUFR/CREX表B

* `BUFR4/BUFRCREX_TableB_en`{usc}__XX__``.csv`` - BUFR/CREX表B第 _XX_ クラス
* `BUFR4/notes/BUFRCREX_TableB_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFRCREX_TableB_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでクラス番号 _XX_ = 00..63 である。

[[BCBcsv]]
==== CSVの構造

BUFR/CREX表BのCSVは長すぎるのでクラス番号 _XX_ によって分割されている。
各CSVは次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|ClassNo | クラス番号 _XX_
|ClassName_en | クラス名称
|FXY | 表参照符(_FXY_ 形式)
|ElementName_en | 要素名
|BUFR_Unit | BUFRの単位
|BUFR_Scale | BUFRの尺度
|BUFR_ReferenceValue | BUFRの参照値
|BUFR_DataWidth_Bits | BUFRのビット幅
|CREX_Unit | CREXの単位
|CREX_Scale | CREXの尺度
|CREX_DataWidth_Char | CREXの文字数
|Note_en |注記表示(非空白の場合、要素名に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,BUFRCREX_CodeFlag_notes.csvを参照)
|Status |状態
|===

ClassNo および ClassName_en 列はクラス内で全行同一である。
クラスごとに分割表示する際に題字として用いる。
Statusは表示に反映しない<<Status,(後述)>>。
通報式文書の表では
FXY, ElementName_en
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結)
に続いて BUFR_Unit から CREX_DataWidth_Char 列までが表示される。

[[BCBNN]]
==== 注釈CSVの構造

`BUFR4/notes/BUFRCREX_TableB_notes.csv` の構造は
<<GCFNN,GRIB2符号表の注釈CSV>>と同様。

[[BCBNT]]
==== 表注釈CSVの構造

`BUFR4/notes/BUFRCREX_TableB_table.csv` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|tableNo |表番号(クラス番号 _XX_ )
|tableName |表の標題
|noteID |注釈番号(BUFRCREX_TableB_notes.csvを参照)
|notation |注記表示
|===

本表では同一のtableNoの行が複数あることに注意。
BUFR/CREX表Bのうち、クラス _XX_ の表を出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[BCC]]
=== BUFR/CREX表C

表Cは操作記述子operatorsを定義する。

* `BUFR4/BUFR_TableC_en.csv` - BUFR表C本体
* `BUFR4/CREX_TableC_en.csv` - CREX表C本体
* `BUFR4/notes/BUFR_TableC_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFR_TableC_table.csv` - 表のエントリではなく表全体にかかる注を記載

CREX表Cの注釈文情報は用意されていない。
もはや新規のCREX通報式利用は想定されないので、
注釈をリンクで丁寧に表現するまでもなく、
固定の注釈リストを印字してしまえばよいという発想である。

[[BCCcsv]]
==== CSVの構造

BUFR表C `BUFR4/BUFR_TableC_en.csv` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|FXY | 表参照符(_FXY_ 形式)
|OperatorName_en |操作記述子の名称
|OperationDefinition_en |操作記述子の定義
|Note_en |注記表示(非空白の場合、前列に続けて表示)
|noteIDs |注釈番号(コンマ区切り数字列,BUFR_TableC_notes.csvを参照)
|Status |状態
|===

Statusは表示に反映しない<<Status,(後述)>>。
通報式文書では FXY, OperatorName_en, および OperationDefinition_en
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結)
が表示される。

CREX表C `BUFR4/CREX_TableC_en.csv` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|FXY | 表参照符(_FXY_ 形式)
|OperatorName_en |操作記述子の名称
|OperationDefinition_en |操作記述子の定義
|Note_en |注記表示(非空白の場合、前列に続けて表示)
|Status |状態
|===

CREXの注釈データがないので、それを参照する注釈番号もない。
本表ではNote_enのリンク化(<<parsingNotes>>)はできない。

[[BCCNN]]
==== 注釈CSVの構造

`BUFR4/notes/BUFR_TableC_notes.csv` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|noteID |注釈番号(表本体から参照するキー)
|note |注釈文字列
|tableAssociation | 表全体にかかる注釈の場合 `table` が書かれる
|===

注釈番号から注釈文字列を探す使い方では <<GCFNN,GRIB2符号表の注釈CSV>>と同様に扱うことができる。

[[BCCNT]]
==== 表注釈CSVの構造

`BUFR4/notes/BUFR_TableC_table.csv` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|tableName |表の標題(全行同一)
|noteID |注釈番号(BUFRCREX_TableB_notes.csvを参照)
|notation |注記表示
|===

BUFR/CREX表Cを出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[BCD]]
=== BUFR/CREX表D

BUFR/CREX表Dは、複数の記述子を表現する集約記述子を定義する。

* `BUFR4/BUFR_TableD_en`{usc}__XX__``.csv`` - BUFR表D第 _XX_ クラス
* `BUFR4/CREX_TableD_en`{usc}__XX__``.csv`` - CREX表D第 _XX_ クラス
* `BUFR4/notes/BUFR_TableD_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFR_TableD_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここでクラス番号 _XX_ = 00..63 である。

CREX表Dの注釈文情報は、表Cと同様に、用意されていない。

[[BCDcsv]]
==== CSVの構造

`BUFR4/BUFR_TableD_en`{usc}__XX__``.csv`` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|Category | カテゴリ番号 _XX_
|CategoryOfSequences_en | カテゴリ標題
|FXY1 | 集約記述子の _FXY_ (シーケンス内同一)
|Title_en | 集約記述子の標題 (シーケンス内同一)
|SubTitle_en | 集約記述子の副題 (シーケンス内同一)
|FXY2 | 記述子 _FXY_
|ElementName_en | 要素名
|ElementDescription_en | 要素の補足説明
|Note_en | 注釈 (要素名に付記)
|noteIDs | 注釈番号 (BUFR_TableD_notes.csvを参照)
|Status | 状態
|===

通報式文書としては、カテゴリが大分類、シーケンスが小分類で、
その中に FXY2, ElementName_en
(<<parsingNotes,後述>>のように解析・リンク化したNote_enを連結),
ElementDescription_en
が並ぶ表が書かれる。
注釈はカテゴリ末尾にまとめて書かれる。
Statusは表示に反映しない<<Status,(後述)>>。

GRIB2のテンプレートと同様、
BUFR表Dは関係データベースの関係(relation)と異なり、
行の順序に意味がある。
しかも、ひとつのシーケンスの内部に
まったく同一の記述子が複数回出現することがあり得る。
したがって、行単位の差分を単に表示しただけでは
加除訂正の位置が正しく伝わらない可能性がある。
差分前後の行を示せばおそらくこの問題は回避できるだろう。
絶対安全を求めるのであれば、シーケンス単位での変更を示したほうがよいかもしれない。

`BUFR4/CREX_TableD_en`{usc}__XX__``.csv`` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|Category | カテゴリ番号 _XX_
|CategoryOfSequences_en | カテゴリ標題
|FXY1 | 集約記述子の _FXY_ (シーケンス内同一)
|Title_en | 集約記述子の標題 (シーケンス内同一)
|SubTitle_en | 集約記述子の副題 (シーケンス内同一)
|FXY2 | 記述子 _FXY_
|ElementName_en | 要素名
|ElementDescription_en | 要素の補足説明
|Note_en | 注釈 (要素名に付記)
|Status | 状態
|===

BUFRとの相違として、
CREXの注釈データがないので、それを参照する注釈番号もない。
本表ではNote_enのリンク化(<<parsingNotes>>))はできない。

[[BCDNN]]
==== 注釈CSVの構造
`BUFR4/notes/BUFR_TableD_notes.csv`  は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|noteID |注釈番号(表本体から参照するキー)
|note |注釈文字列
|tableAssociation | 表全体にかかる注釈の場合クラス番号 _XX_ が書かれる
|===

注釈番号から注釈文字列を探す使い方では <<GCFNN,GRIB2符号表の注釈CSV>>と同様に扱うことができる。

[[BCDNT]]
==== 表注釈CSVの構造

`BUFR4/notes/BUFR_TableD_table.csv`  は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|tableNo |表番号(クラス番号 _XX_ )
|tableName |表の標題
|noteID |注釈番号(BUFR_TableD_notes.csvを参照)
|notation |注記表示
|===

扱いは<<BCBNT,表Bの表注釈CSV>>と同様。
本表では同一のtableNoの行が複数あることに注意。
BUFR表Dのうち、クラス _XX_ の表を出力するとき、
各行に付された注釈に加えて、本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[CCT]]
=== 共通符号表

* `CCT/COV.csv` - 共通符号表一覧
* ``CCT/C``__cc__``.csv`` - 共通符号表 C-_cc_
* `CCT/notes/CCT_notes.csv` - 注釈番号から注釈文を与える
* `CCT/notes/CCT_table.csv` - 表のエントリではなく表全体にかかる注を記載

ここで表番号 _cc_ = 00,01,...,08,11,...,14 である。
共通符号表は _cc_ により列構造が異なる。

[[CCTcov]]
==== 共通符号表一覧の構造

`CCT/COV.csv` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|CommonCodeTable |共通符号表番号。なぜか __c__``.00`` の形式 (各表同一)
|Title_en |各表の名称 (各表同一)
|Applicable_en |通報式と使用場所
|Status |状態
|===

CommonCodeTable 列は例えば _cc_=01 であれば `1.00` の形式である。
WMOの通報式文書では共通符号表のセクションの冒頭に
共通符号表ごとに Title_en に続けて
Applicable_en を列挙した一覧が置かれている。
日本の「国際気象通報式 別冊」にはこの部分がない。
Statusは表示に反映しない<<Status,(後述)>>。

一部の共通符号表は通報式により異なる複数の符号体系を定義する。
その場合、本表をCommonCodeTableの値で検索すると複数の行が見つかる。

[[CCTcsv]]
==== CSVの構造

``CCT/C``__cc__``.csv`` は次の列を持つ:

[cols="1,6,1,1",option="header"]
|===
|_cc_ |列名 |注釈 |Status 
|00 |**GRIB version number, BUFR version number, CREX version number**, Effective date |{mdash} |Status
|01 |**CodeFigureForF1F2, CodeFigureForF3F3F3, Octet5GRIB1_Octet6BUFR3**, OriginatingGeneratingCentres_en |{mdash} |Status
|02 |DateOfAssignment_en, **CodeFigureForrara, CodeFigureForBUFR**, RadiosondeSoundingSystemUsed_en |&#x2014; |Status
|03 |**CodeFigureForIXIIXIX, CodeFigureForBUFR**, InstrumentMakeAndType_en, EquationCoefficients_a, EquationCoefficients_b |{mdash} |Status
|04 |**CodeFigureForXRXR, CodeFigureForBUFR**, Meaning_en |{mdash} |Status
|05 |**CodeFigureForI6I6I6, CodeFigureForBUFR, CodeFigureForGRIB2**, SatelliteName_en |{mdash} |Status
|06 |**CodeFigure**, UnitType, Meaning, conventional, IA5-ASCII,
ITA2,SIDefinition |Note, NoteID |Status
|07 |**CodeFigureForsasa, CodeFigureForBUFR**, TrackingTechniquesStatusOfSystemUsed_en |{mdash} |Status
|08 |**Code**, Agency_en, Type_en, InstrumentShortName_en, InstrumentLongName_en |{mdash} |Status
|11 |**CREX2, GRIB2_BUFR4**, OriginatingGeneratingCentre_en |{mdash} |Status
|12 |**CodeFigure_OriginatingCentres**, Name_OriginatingCentres_en, **CodeFigure_SubCentres**, Name_SubCentres_en |{mdash} |Status
|13 |**CodeFigure_DataCategories**, Name_DataCategories_en, **CodeFigure_InternationalDataSubcategories**, Name_InternationalDataSubcategories_en |{mdash} |Status
|14 |*CodeFigure*, Meaning_en, ChemicalFormula |{mdash} |Status
|===

共通符号表はいずれも符号に意味を与えるものである。
ひとつの表が<<CCTcov>>で示されるように
通報式により異なる符号を定義する場合は符号の列が複数になる。

一部の表では符号の前に限定がつく。
CCT-C02 は符号位置が枯渇しているため、再割当てを区別するために
割当日付を入れている。
CCT-C12 及び CCT-C13 はそれぞれ発信中枢ごと及びデータカテゴリごとに
符号の意味が異なるため区別のために用いられる。

CCT-C06 にだけ注釈がつけられる。

表示としては、限定、符号、意味の各列を列挙すれば一応の形になる。
Status 列は CCT-C14 で Extension という値があり、
これを有する行は表示から除外すべきである
<<Status,(後述)>>。


//HEAD
[[CCTNN]]
==== 注釈CSVの構造
`CCT/notes/CCT_notes.csv`
は注釈番号から注釈文を与えるもので、
構造は<<GCFNN,GRIB2符号表の注釈CSV>>と同様。

[[CCTNT]]
==== 表注釈CSVの構造
`CCT/notes/CCT_table.csv` は次の列を持つ:

[cols="1,3",option="header"]
|===
|列名 |名称・用法 
|tableNo |共通符号表番号 _cc_
|tableName |表の標題
|noteID |注釈番号(CCT_notes.csvを参照)
|notation |注記表示
|===

本表では同一のtableNoの行が複数あることに注意。
共通符号表 ``C``__cc__ の表を出力するとき、
各行に付された注釈に加えて、
本表をスキャンしてすべての注釈を列挙して、
注記表示番号順に表示する。

[[Status]]
=== (各表共通) Status列

多くの表にStatus列がある。その意味は次のとおり

* Operational {mdash} 現用の通報式
* Deprecated {mdash} 現用の通報式だが、廃止予定と宣言
* Experimental {mdash} 通報式には掲載するが、バリデーションが未了との注記を付す
* Extension {mdash} CCT C-14 で使われる。現用通報式には掲載されていない行。

なお、次の品質的問題がある。

* 一部空欄になっている場合がある。
  CCT C-06 では Operational と解せばよいが
  GRIB2テンプレート3.1000 は Experimental とすべきだろう。
  脱字として処理すべき。
* Operational は様々な typo がある（Oprational, Operatonal,
  Operationaal など、また前後にスペース付加も)

処理としては、 Deprecated のある行に注記を付加し、
Extension のある行を削除するのが妥当と推定。

*TODO*: Deprecatedの用例について通報式文書を確認し、注記付加処理でよいか確認

日本ローカル定義のデータを収めたファイルでは次の2種類を認識する:

* Replace {mdash} 国際共通表から削除する行
* Local {mdash} 国際共通表に追加する行

Replace 指定がある行を探索し、それを削除し、
その位置に、続く Local 指定がある行を挿入する。
Status=Replace であり、他の列が空の行は、表示表の末尾への追加を意味する。

[[SYMBOLS]]
== 本文書で用いた記号

[cols="1,2,5",options="header"]
|===
|記号 |範囲 |意味 
|_cc_ |0以上（現在14まで使用） |共通符号表番号
|_d_ |0-255 |GRIB2符号表4.2で用いる分野(discipline)番号
|_F_ |0-3 |BUFR/CREX の記述子の _F_ 部、十進表現1桁
|_FXY_ | |BUFR/CREXの記述子の _F,X,Y_ 部を十進表現1,2,3桁で並べたもの
|_k_ |0-255 |GRIB2符号表4.2で用いるカテゴリ(category)番号
|_n_ |0以上 (現在336まで使用) |GRIB2の符号・フラグ表の番号
|_nnnnn_ |〃 |GRIB2の符号・フラグ表の番号、十進表現5桁
|_s_ |1,3,4,5,7 |GRIB2の節(section)番号
|_s.n.d.k_ | |GRIB2の符号表を識別する番号 _s,n,d,k_ (欠はゼロで補う)をピリオド区切りで並べたもの
|_t_ |0-65535 |GRIB2のテンプレート番号
|_ttttt_ |〃 |GRIB2のテンプレート番号、十進表現5桁
|_XX_ |0-63 |BUFR/CREX の記述子の _X_ 部 (要素記述子ではクラス(class)番号という)、十進表現2桁ゼロ前置
|_YYY_ |0-255 |BUFR/CREX の記述子の _Y_ 部、十進表現3桁ゼロ前置
|===
