= TDCF通報式WMO CSV表の処理
:toc:
:usc: _

== WMO CSVのファイル構造
=== レポジトリ
次の3つのレポジトリに分かれて管理されている:

* https://github.com/wmo-im/GRIB2
* https://github.com/wmo-im/BUFR4 (CREXを含む)
* https://github.com/wmo-im/CCT

ブランチ:

* `main` - 現行最新通報式
* `FT2026-1` - 照会中ファストトラック
* `FT2025-2` (削除済み) - 前回のファストトラック

=== ファイル名

==== GRIB2符号表
* `GRIB2/GRIB2_CodeFlag`{usc}__a{usc}b__``{usc}CodeTable{usc}en.csv`` - 符号表__a__._b_
* `GRIB2/GRIB2_CodeFlag`{usc}__a{usc}b__``{usc}FlagTable{usc}en.csv`` - フラグ表__a__._b_
* `GRIB2/GRIB2_CodeFlag`{usc}4{usc}2{usc}__c{usc}d__``{usc}CodeTable{usc}en.csv`` - 符号表4.2分野__c__カテゴリ__d__
* `GRIB2/notes/CodeFlag_notes.csv` - 注釈番号から注釈文を与える
* `GRIB2/notes/CodeFlag_table.csv` - 表のエントリではなく表全体にかかる注を記載

==== GRIB2テンプレート
* `GRIB2/GRIB2_Template{usc}1`{usc}__b__{usc}``IdentificationTemplate_en.csv`` - 識別テンプレート1.__b__
* `GRIB2/GRIB2_Template{usc}3`{usc}__b__{usc}``GridDefinitionTemplate_en.csv`` - 格子系定義テンプレート3.__b__
* `GRIB2/GRIB2_Template_4`{usc}__b__{usc}``ProductDefinitionTemplate_en.csv`` - プロダクト定義テンプレート4.__b__
* `GRIB2/GRIB2_Template_5`{usc}__b__{usc}``DataRepresentationTemplate_en.csv`` - 資料表現テンプレート5.__b__
* `GRIB2/GRIB2_Template_7`{usc}__b__{usc}``DataTemplate_en.csv`` - 資料テンプレート7.__b__
* `GRIB2/notes/Template_notes.csv` - 注釈番号から注釈文を与える
* `GRIB2/notes/Template_table.csv` - 表のエントリではなく表全体にかかる注を記載

==== BUFR/CREX符号表

* `BUFR4/BUFRCREX_CodeFlag_en`{usc}__n__``.csv`` - 符号・フラグ表第 _n_ クラス
* `BUFR4/notes/BUFRCREX_CodeFlag_notes.csv` - 注釈番号から注釈文を与える
* `BUFR4/notes/BUFRCREX_CodeFlag_table.csv` - 表のエントリではなく表全体にかかる注を記載

* `notes/`*`_notes.csv` - 注釈番号から注釈文を与える
* `notes/`*`_table.csv` - 表のエントリではなく表全体にかかる注を記載
